### ISSUE TITLE
Love the new features. Ready for test errors?

### ISSUE THREAD

**Issue by jdar** [code-and-effect/effective_website#14]
Hi Matt,

I downloaded a pristine copy and tried to run the tests.

Do you want a copy of my test output, with some superficial-looking errors? I know you just released the newest update, and this feedback may be premature. 

For example, the following test failure looks, to my eye, to be a data-model change from some previous version of the code...

  crud_test: (clients#index)                                      FAIL (9.12s)
        (assigns) Expected @clients or @datatable to be present
        effective_test_bot (1.1.21) test/test_botable/crud_test.rb:28:in `test_bot_index_test'

**Comment by matt-riemer** [comment]
Hey great feedback, I'm glad someone is running that effective test bot :)

I would expect the `rails test` and `rails test:system` to run without errors. But the test bot might be tripping up on a few non-crud pages.  This is expected.

Thanks!
