### ISSUE TITLE
"Browse server" in rich text editor

### ISSUE THREAD

**Issue by jdar** [code-and-effect/effective_website#3]
First off, thank you for creating this plugable architecture and example. I am just looking around. I hope this very minor bugreport will help.

While exploring, I created a page and edited the content.  I do not have https or CORS configured.

Starting to create a link I clicked on "Browse server" and received a Routing Error with the information below: 

http://localhost:3000/effective/assets?CKEditor=footer_left&CKEditorFuncNum=121&langCode=en

Routing Error
No route matches [GET] "/effective/assets"
Rails.root: /Users/username/src/effective_website

Application Trace | Framework Trace | Full Trace
Routes
[...]

Request
Parameters:

{"CKEditor"=>"footer_left", "CKEditorFuncNum"=>"121", "langCode"=>"en"}
Toggle session dump
_csrf_token: "jJn5kbKgNN+ueSTN4U1s7j8FwCwj2zPBYVhN8Hl6pOA="
session_id: "2531b2bd8b980a9e907f5b0660a63ac6"
warden.user.user.key: [[1], "$2a$11$.8v3vNWG1RlstDKULMlMge"]
Toggle env dump
GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.9,es;q=0.8"
HTTP_VERSION: "HTTP/1.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "::1"
SERVER_NAME: "localhost"
SERVER_PROTOCOL: "HTTP/1.1"
Response

Headers:

None

**Comment by matt-riemer** [comment]
Hey @jdar 

Great catch! :)

Yep, I'm aware of this one.

If you want that built in functionality, you can also install the effective_assets gem.

But this version of effective_website is using all the new ActiveStorage, which I haven't built out for that ckeditor asset uploader yet :)

You can just drag & drop images into any editable region and it will work, saving the image in base64-encoding right within the region itself.

Good luck!

**Comment by jdar** [comment]
Hi Matt,

Ah, ok. 

Let me know if you want other small issues to be opened on effective_* as tickets, such as effective_developer "effective:scaffold" producing a model file "app/models/.rb"

default: I will assume you do NOT want additional tickets, until things are more stable.

Thanks for your time.
